name: PM-Beacons
main: jasonwynn10\beacon\Beacons
version: 1.0.6
api:
 - 3.0.0
description: "Beacons for PocketMine-MP exactly like Vanilla!"
author: "jasonwynn10"
mcpe-protocol:
 - 407
 - 408
 - 419
 - 422
